[package]
name = "clog"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.3"
pest_derive = "2.8.3"

serde = { version = "1.0", features = ["derive"]}
chrono = { version = "0.4", features = ["serde"]}
